pipeline {
    agent { label 'linux' }
    stages {      
        stage('Cleanup') {
            steps {
                sh 'docker-compose stop production-request development-request'
                sh 'docker-compose rm production-request development-request'
                sh 'rm -r *'
            }
        }
        stage('Clone') {
            steps {
                sh 'git clone https://github.com/Emmvish/Sociocon.git .'
                sh "find . -mindepth 1  ! -regex '^./request\(/.*\)?' -delete"
            }
        }
        stage('Test & Deploy') {
            steps {
                sh 'cd request && docker-compose up --detach --build production-request development-request'
            }
        }
    }
}