version: '3'
services: 
  production-bond:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    env_file:
      - ./config/config.env
  development-bond:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
        - "${MONGODB_PORT}:${MONGODB_PORT}"
    env_file:
        - ./config/config.env